name: Build telek

on:
  workflow_dispatch:
  watch:
   types: [started]

defaults:
  run:
   shell: bash

jobs:
 buildtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with: 
          swap-size-gb: 5
         
      - name: setup package
        run: |
         sudo apt-get update -y && sudo apt-get install dialog bash sed wget git curl zip tar jq expect make cmake automake autoconf llvm lld lldb gcc binutils bison perl gperf gawk flex bc python3 zstd openssl unzip cpio bc bison build-essential ccache liblz4-tool libsdl1.2-dev libstdc++6 libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zlib1g-dev libncurses5-dev bzip2 git gcc g++ libssl-dev gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf gcc-arm-linux-gnueabi dos2unix kmod python2 aria2 -y
         
      - name: cloning KernelSU
        run: |
         curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: clean up
        run: |
         make clean; make mrproper; rm -rf out

      - name: check clang version
        run: |
         clang -v
         
      - name: start up
        run: |
         chmod +x build
         ./build

      - name: anykernel ~ zipping
        run: |
         git clone https://github.com/nathannxx/AnyKernel3 ~/any/ && \
         cp -r ~/out/arch/arm64/boot/Image.gz-dtb ~/any/ && \
         cd ~/any/ && zip -r9 KernelSU-${{ github.run_id }}.zip *
        
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
           files: |
            /home/runner/any/KernelSU*
           name: KernelSU-${{ github.run_id }}
           tag_name: ${{ github.run_id }}
        env:
         GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
